"""editing relationships

Revision ID: c9ad0e5f2e8d
Revises: 5883a062073c
Create Date: 2021-09-13 15:39:21.456944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9ad0e5f2e8d'
down_revision = '5883a062073c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'receiver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'receiver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
